### ISSUE TITLE
[Bug]: Holding any item will allow travelling through a gate when required is set to true.

### ISSUE THREAD

**Issue by meridianrealms** [Mrbysco/DimensionalItemGate#1]
### General Info

- [ ] I am running a modpack
- [x] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the mod

### Forge version

47.2.19

### Minecraft version

1.20.1

### Mod version

1.0.0

### Java version

17.0.8

### Issue Description

When setting "required": "true", holding any item will allow you to pass through the portal. I've tested with both Nether and End portals and with various items with the same results. Holding nothing will trigger the message and cancel the teleport event. My config file is below. It's just a modified version of the example script.

```json
{
  "type": "dimensional_itemgate:recipe",
  "ingredients": [
    {
      "tag": "minecraft:diamond"
    }
  ],
  "required": "true",
  "dimension": "minecraft:the_nether"
}
```

**Comment by Mrbysco** [comment]
A fix is being uploaded, I've also fixed the example being wrong

**Comment by meridianrealms** [comment]
Thank you for the super fast fix!
